[build]
  command = "npm run build"
  publish = "public"
  
[[redirects]]
  from = "/build/assets/*"
  to = "/build/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200