[build]
  command = "npm run build"
  publish = "public"
  
[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false